#!/usr/bin/env bash
# Fix JetBrains/PyCharm Remote Dev on NFS/CIFS/AUTOFS homes
# - Per-user, no sudo required
# - Idempotent; safe to run multiple times
# - Sets XDG* dirs and TMPDIR to per-user dirs (defaults under /tmp)
# - Makes env apply to non-interactive SSH via ~/.pam_environment, ~/.ssh/rc, and ~/.profile (login shells)
# - Optional: purge old JetBrains caches with --purge
#
# Why this exists:
# JetBrains Remote Dev often uses a login shell (bash -lc), so ~/.profile can override XDG_*.
# If XDG_CACHE_HOME is set to a shared path like /tmp/jetbrains_cache, one user's permissions can break everyone.
# This script forces per-user paths (e.g., /tmp/jetbrains_$USER/cache) to avoid collisions.

set -euo pipefail

PURGE=0
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --purge) PURGE=1 ;;
    --force) FORCE=1 ;;
    -h|--help)
      cat <<'USAGE'
Usage: fix_jetbrains_remote.sh [--purge] [--force]

  --purge  Remove stale JetBrains caches in $HOME and /tmp to force clean backend reinstall
  --force  Rewrite env files even if they already look correct

Environment overrides:
  JB_REMOTE_ROOT   Base directory to use (default: /tmp, fallback: /var/tmp)
                   Example: JB_REMOTE_ROOT=/var/tmp bash fix_jetbrains_remote.sh
USAGE
      exit 0
      ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

USER_NAME="${USER:-$(id -un)}"
HOME_DIR="${HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}"

# Detect FS type of $HOME (fallback to /home)
FS_TYPE="$(findmnt -n -o FSTYPE --target "$HOME_DIR" 2>/dev/null || true)"
if [[ -z "$FS_TYPE" ]]; then
  FS_TYPE="$(findmnt -n -o FSTYPE /home 2>/dev/null || true)"
fi

NEEDS_FIX=0
if [[ "$FS_TYPE" =~ ^(nfs|nfs4|cifs|smbfs|autofs)$ ]]; then
  NEEDS_FIX=1
fi

# Choose a per-user base dir. Default to /tmp (fast, local) but keep a fallback.
# IMPORTANT: ensure the base is per-user to avoid cross-user permission conflicts.
BASE_ROOT="${JB_REMOTE_ROOT:-/tmp}"
BASE_ROOT="${BASE_ROOT%/}"

pick_paths() {
  local root="$1"
  root="${root%/}"
  # Per-user root to avoid collisions:
  #   /tmp/jetbrains_<user>/...
  JET_BASE="$root/jetbrains_${USER_NAME}"
  XDG_CACHE="$JET_BASE/cache"
  XDG_CONFIG="$JET_BASE/config"
  XDG_DATA="$JET_BASE/data"
  TMP_DIR="$JET_BASE/tmp"
}

try_make_dirs() {
  mkdir -p "$XDG_CACHE" "$XDG_CONFIG" "$XDG_DATA" "$TMP_DIR" 2>/dev/null || return 1
  chmod 700 "$JET_BASE" "$XDG_CACHE" "$XDG_CONFIG" "$XDG_DATA" "$TMP_DIR" 2>/dev/null || true
  # Ensure we can actually write here
  test -w "$XDG_CACHE" && test -w "$TMP_DIR"
}

pick_paths "$BASE_ROOT"
if ! try_make_dirs; then
  # Fallback to /var/tmp (often more permissive/persistent)
  pick_paths "/var/tmp"
  if ! try_make_dirs; then
    echo "ERROR: Could not create per-user JetBrains dirs under '$BASE_ROOT' or '/var/tmp'." >&2
    echo "       Tried: $JET_BASE" >&2
    echo "       Check permissions / quotas / mount options." >&2
    exit 1
  fi
fi

# Helper: ensure a key=value pair exists in ~/.pam_environment with DEFAULT= form
ensure_pam_env() {
  local key="$1" val="$2"
  local file="$HOME_DIR/.pam_environment"
  touch "$file"
  if grep -qE "^\s*${key}\s+" "$file"; then
    if [[ "$FORCE" -eq 1 ]]; then
      sed -i.bak -E "s|^\s*${key}\s+.*$|${key} DEFAULT=${val}|" "$file"
    fi
  else
    printf "%s DEFAULT=%s\n" "$key" "$val" >> "$file"
  fi
}

# Helper: ensure export line exists in ~/.ssh/rc
ensure_ssh_rc_export() {
  local key="$1" val="$2"
  local file="$HOME_DIR/.ssh/rc"
  mkdir -p "$HOME_DIR/.ssh"
  touch "$file"
  if ! grep -qE "^\s*export\s+${key}=" "$file"; then
    printf "export %s=%q\n" "$key" "$val" >> "$file"
  elif [[ "$FORCE" -eq 1 ]]; then
    # Replace existing (keep shell-quoting stable)
    grep -vE "^\s*export\s+${key}=" "$file" > "$file.tmp" || true
    printf "export %s=%q\n" "$key" "$val" >> "$file.tmp"
    mv "$file.tmp" "$file"
  fi
  chmod 700 "$file"
}

# Helper: ensure a managed block exists at the end of ~/.profile
# This is crucial because JetBrains Remote Dev runs "bash -lc" (login shell)
# and ~/.profile can override pam_env.
ensure_profile_block() {
  local file="$HOME_DIR/.profile"
  touch "$file"
  local start="# >>> jetbrains_remote_fix >>>"
  local end="# <<< jetbrains_remote_fix <<<"
  local block

  # NOTE: We write absolute paths discovered by this script (per-user), and we place this block at
  # the end of ~/.profile so it overrides earlier exports like XDG_CACHE_HOME=/tmp/jetbrains_cache.
  block="${start}
# Generated by fix_jetbrains_remote.sh
# Keep these per-user to avoid shared /tmp permission conflicts.
export XDG_CACHE_HOME=\"${XDG_CACHE}\"
export XDG_CONFIG_HOME=\"${XDG_CONFIG}\"
export XDG_DATA_HOME=\"${XDG_DATA}\"
export TMPDIR=\"${TMP_DIR}\"
${end}"

  if grep -qF "$start" "$file"; then
    if [[ "$FORCE" -eq 1 ]]; then
      # Replace existing managed block
      awk -v start="$start" -v end="$end" -v repl="$block" '
        BEGIN{in=0}
        index($0,start)==1 {print repl; in=1; next}
        in==1 && index($0,end)==1 {in=0; next}
        in==1 {next}
        {print}
      ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
    fi
  else
    printf "\n%s\n" "$block" >> "$file"
  fi
}

# Compute current state signature to decide idempotency
CURRENT_SIG="$(printf "%s|%s|%s|%s|%s" "$FS_TYPE" "$XDG_CACHE" "$XDG_CONFIG" "$XDG_DATA" "$TMP_DIR" | shasum | awk '{print $1}')"
STATE_DIR="$HOME_DIR/.config/jetbrains_remote_fix"
STATE_FILE="$STATE_DIR/state.sig"
mkdir -p "$STATE_DIR"

# If not on a network FS, we still allow setup (harmless), but inform user
if [[ "$NEEDS_FIX" -eq 0 ]]; then
  echo "Note: $HOME appears to be on '$FS_TYPE' (not nfs/cifs/autofs). Proceeding anyway (safe)."
fi

# Apply ~/.pam_environment (works for non-interactive SSH via pam_env)
ensure_pam_env "XDG_CACHE_HOME" "$XDG_CACHE"
ensure_pam_env "XDG_CONFIG_HOME" "$XDG_CONFIG"
ensure_pam_env "XDG_DATA_HOME"  "$XDG_DATA"
ensure_pam_env "TMPDIR"         "$TMP_DIR"

# Also set in ~/.ssh/rc for robustness (SSH-only sessions)
ensure_ssh_rc_export "XDG_CACHE_HOME" "$XDG_CACHE"
ensure_ssh_rc_export "XDG_CONFIG_HOME" "$XDG_CONFIG"
ensure_ssh_rc_export "XDG_DATA_HOME"  "$XDG_DATA"
ensure_ssh_rc_export "TMPDIR"         "$TMP_DIR"

# And ensure ~/.profile exports the same values (JetBrains uses bash -lc)
ensure_profile_block

# Quick SFTP sanity (non-fatal)
if command -v sftp >/dev/null 2>&1; then
  if sftp -b /dev/null -q "$USER_NAME@$(hostname -f 2>/dev/null || hostname)" 2>/dev/null; then
    echo "SFTP sanity: OK (loopback to this host succeeded)."
  else
    echo "SFTP sanity: could not verify via loopback (this is fine if you're configuring a different remote)."
  fi
else
  echo "SFTP not found in PATH; skipping SFTP check."
fi

# Warn if chosen base is mounted noexec
if mount | awk '{print $3,$6}' | grep -E "(^${JET_BASE%/*} | on ${JET_BASE%/*} )" | grep -q noexec; then
  echo "WARNING: ${JET_BASE%/*} is mounted with 'noexec'. JetBrains backend may fail to start there."
fi

# Optional purge of old JetBrains caches to force clean backend install
if [[ "$PURGE" -eq 1 ]]; then
  echo "Purging old JetBrains caches (safe; only caches/backends)…"
  rm -rf "$HOME_DIR/.cache/JetBrains" "$HOME_DIR/.local/share/JetBrains" \
         "$XDG_CACHE/JetBrains" "$XDG_DATA/JetBrains" \
         "/tmp/JetBrains-*" \
         "/tmp/jetbrains_cache" "/tmp/jetbrains_config" "/tmp/jetbrains_data" \
         2>/dev/null || true
fi

# Determine if anything changed since last run (very simple check)
PREV_SIG=""
if [[ -f "$STATE_FILE" ]]; then
  PREV_SIG="$(cat "$STATE_FILE" || true)"
fi

if [[ "$CURRENT_SIG" == "$PREV_SIG" && "$FORCE" -eq 0 && "$PURGE" -eq 0 ]]; then
  echo "JetBrains remote env already configured. Nothing to do."
  exit 0
fi

echo "$CURRENT_SIG" > "$STATE_FILE"

cat <<EOF
✔ JetBrains Remote Dev env prepared for user '$USER_NAME'
   FS type of \$HOME: ${FS_TYPE:-unknown}
   Base dir        = ${JET_BASE%/*}
   XDG_CACHE_HOME  = $XDG_CACHE
   XDG_CONFIG_HOME = $XDG_CONFIG
   XDG_DATA_HOME   = $XDG_DATA
   TMPDIR          = $TMP_DIR

Next steps:
  1) Disconnect and reconnect the PyCharm Remote Dev / SSH Interpreter session.
  2) If it still errors, run once with '--purge' to force a clean backend reinstall.

Tip:
  These settings apply on next SSH session (via pam_env, ~/.ssh/rc, and ~/.profile). If you're already logged in, reconnect.
EOF
